services:
  db:
    container_name: mail_mysql
    image: mysql:latest
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mail
      - MYSQL_DATABASE=mail
    ports:
      - "3306:3306"

  redis:
    container_name: mail_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"