services:
  db:
    container_name: concurrency_mysql
    image: mysql:latest
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=concurrency
      - MYSQL_DATABASE=concurrency
    ports:
      - "3306:3306"

  redis:
    container_name: concurrency_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"