services:
  querydsl:
    container_name: querydsl
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: querydsl
      MYSQL_DATABASE: querydsl
    volumes:
      - ./mysql_data:/var/lib/mysql