services:
  mysql-optimization:
    image: mysql:latest
    container_name: mysql-optimization
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: